### ISSUE TITLE
Move time slider + emoji between your project + other people's projects

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#118]
Move it up from the bottom

**Comment by paulinahaduong** [comment]
Related Q the buttons are stable (b/c of cookies, right?); when you come back, does the slider move?

**Comment by jsarchibald** [comment]
@paulinahaduong none of this is implemented right now because I wanted to wait for us to figure out the spec first (so these questions are useful).

What I was thinking:
- If there's no submission recorded, then show the reflection form.
- When the form is submitted, associate the submission with a randomly-generated identifier for the browser (stored in a cookie).
- When reloading the page, check if there's a submission for this project. If there is, check the identifier against the cookie. If this is the same browser used to submit the form, show the form again with values filled in (and still able to edit).

I think it makes most sense to be able to reflect the submission back to the user.

**Comment by paulinahaduong** [comment]
That makes a lot of sense and I agree with you! My Q about overwriting is an internal one - would we have 2 entries in our log or just 1 if someone comes back and changes their response?

**Comment by jsarchibald** [comment]
Most likely I'll just add entries for each submission because it's easier to implement (and also gives us the advantage of keeping more data -- maybe a user changes their reaction for some reason? why?). Whether you see one or several is up to you; it shouldn't be hard to filter out earlier responses as needed.

**Comment by paulinahaduong** [comment]
That sounds great! We would definitely prefer that over anything being overwritten. :)
